<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTapfiliateIntegrationTables extends Migration
{
    public function up()
    {
        // To map your users to Tapfiliate's affiliate IDs and referral codes
        Schema::create('tapfiliate_user_mappings', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->onDelete('cascade');
            $table->string('tapfiliate_affiliate_id')->nullable()->unique(); // Tapfiliate's unique affiliate ID
            $table->string('referral_code')->nullable()->unique(); // The referral code generated by Tapfiliate
            $table->boolean('is_active')->default(true);
            $table->timestamps();
            
            $table->index('referral_code');
        });

        // Optional: To track custom rewards applied within your app (e.g., store credits)
        Schema::create('custom_rewards', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->onDelete('cascade'); // Recipient of the reward
            $table->enum('reward_type', ['credit', 'points', 'custom'])->default('points');
            $table->decimal('amount', 10, 2);
            $table->string('currency', 3)->default('EUR');
            $table->string('status')->default('pending'); // e.g., pending, approved, applied, cancelled
            $table->string('tapfiliate_conversion_id')->nullable(); // Link to the Tapfiliate conversion that triggered this
            $table->text('description')->nullable();
            $table->timestamps();
            
            $table->index(['user_id', 'reward_type', 'status']);
        });
    }

    public function down()
    {
        Schema::dropIfExists('custom_rewards');
        Schema::dropIfExists('tapfiliate_user_mappings');
    }
}
