<?php

return [
    'max_preview_rows' => 5,
    'max_upload_kb' => 4096,

    'columns' => [
        ['key' => 'category', 'label' => 'Category', 'required' => true, 'description' => 'Use an existing vehicle category name, slug, or id from your account. This also affects SIPP generation.', 'example' => 'Luxury'],
        ['key' => 'brand', 'label' => 'Brand', 'required' => true, 'description' => 'Vehicle brand', 'example' => 'BMW'],
        ['key' => 'model', 'label' => 'Model', 'required' => true, 'description' => 'Vehicle model', 'example' => 'X5'],
        ['key' => 'body_style', 'label' => 'Body Style', 'required' => true, 'description' => 'Use one of the allowed body styles exactly, such as sedan or suv. This affects SIPP generation.', 'example' => 'suv'],
        ['key' => 'transmission', 'label' => 'Transmission', 'required' => true, 'description' => 'Use an allowed value exactly, such as manual or automatic. This affects SIPP generation.', 'example' => 'automatic'],
        ['key' => 'fuel', 'label' => 'Fuel', 'required' => true, 'description' => 'Use an allowed fuel value exactly, such as petrol, diesel, hybrid, or electric. This affects SIPP generation.', 'example' => 'diesel'],
        ['key' => 'air_conditioning', 'label' => 'Air Conditioning', 'required' => true, 'description' => 'Use yes/no or 1/0. This affects SIPP generation.', 'example' => 'yes'],
        ['key' => 'seating_capacity', 'label' => 'Seats', 'required' => true, 'description' => 'Numeric seat count. This affects SIPP generation.', 'example' => '5'],
        ['key' => 'number_of_doors', 'label' => 'Doors', 'required' => true, 'description' => 'Numeric door count. This affects SIPP generation.', 'example' => '5'],
        ['key' => 'color', 'label' => 'Color', 'required' => true, 'description' => 'Vehicle color', 'example' => 'Black'],
        ['key' => 'status', 'label' => 'Status', 'required' => true, 'description' => 'Listing status', 'example' => 'available'],
        ['key' => 'vendor_location_code', 'label' => 'Vendor Location', 'required' => true, 'description' => 'Use a saved vendor location id, code, name, or IATA code from your account', 'example' => 'Amsterdam Airport'],
        ['key' => 'registration_number', 'label' => 'Registration Number', 'required' => true, 'description' => 'Vehicle registration number', 'example' => 'AB-123-CD'],
        ['key' => 'registration_country', 'label' => 'Registration Country', 'required' => true, 'description' => 'ISO country code or country name', 'example' => 'NL'],
        ['key' => 'registration_date', 'label' => 'Registration Date', 'required' => true, 'description' => 'Format: YYYY-MM-DD', 'example' => '2024-01-15'],
        ['key' => 'phone_number', 'label' => 'Phone Number', 'required' => true, 'description' => 'Vendor contact phone', 'example' => '+31612345678'],
        ['key' => 'price_per_day', 'label' => 'Price Per Day', 'required' => true, 'description' => 'Daily price in vendor currency', 'example' => '89.00'],
        ['key' => 'price_per_week', 'label' => 'Price Per Week', 'required' => false, 'description' => 'Weekly price when used by your pricing model', 'example' => '540.00'],
        ['key' => 'weekly_discount', 'label' => 'Weekly Discount', 'required' => false, 'description' => 'Optional weekly discount amount', 'example' => '35.00'],
        ['key' => 'price_per_month', 'label' => 'Price Per Month', 'required' => false, 'description' => 'Monthly price when used by your pricing model', 'example' => '1890.00'],
        ['key' => 'monthly_discount', 'label' => 'Monthly Discount', 'required' => false, 'description' => 'Optional monthly discount amount', 'example' => '120.00'],
        ['key' => 'price_per_km', 'label' => 'Price Per KM', 'required' => false, 'description' => 'Optional overage price per kilometre', 'example' => '0.35'],
        ['key' => 'security_deposit', 'label' => 'Security Deposit', 'required' => true, 'description' => 'Security deposit amount', 'example' => '350.00'],
        ['key' => 'minimum_driver_age', 'label' => 'Minimum Driver Age', 'required' => true, 'description' => 'Minimum driver age', 'example' => '23'],
        ['key' => 'mileage', 'label' => 'Mileage', 'required' => true, 'description' => 'Vehicle mileage / efficiency value used by the current listing form', 'example' => '16'],
        ['key' => 'luggage_capacity', 'label' => 'Luggage Capacity', 'required' => false, 'description' => 'Number of luggage pieces', 'example' => '4'],
        ['key' => 'horsepower', 'label' => 'Horsepower', 'required' => true, 'description' => 'Engine horsepower', 'example' => '240'],
        ['key' => 'co2', 'label' => 'CO2', 'required' => true, 'description' => 'CO2 emissions', 'example' => '130'],
        ['key' => 'gross_vehicle_mass', 'label' => 'Gross Vehicle Mass', 'required' => false, 'description' => 'Optional vehicle specification value', 'example' => '2100'],
        ['key' => 'vehicle_height', 'label' => 'Vehicle Height', 'required' => false, 'description' => 'Optional vehicle height value', 'example' => '1.72'],
        ['key' => 'dealer_cost', 'label' => 'Dealer Cost', 'required' => false, 'description' => 'Optional internal cost value', 'example' => '55.00'],
        ['key' => 'fuel_policy', 'label' => 'Fuel Policy', 'required' => false, 'description' => 'Fuel policy', 'example' => 'full_to_full'],
        ['key' => 'guidelines', 'label' => 'Guidelines', 'required' => false, 'description' => 'Vendor instructions for renters', 'example' => 'Bring passport and driving license'],
        ['key' => 'terms_policy', 'label' => 'Terms Policy', 'required' => false, 'description' => 'Optional terms and policy text shown to renters', 'example' => 'No smoking. Return with the agreed fuel level.'],
        ['key' => 'rental_policy', 'label' => 'Rental Policy', 'required' => false, 'description' => 'Optional long-form rental policy text', 'example' => 'Late return, cleaning, insurance, and damage rules.'],
        ['key' => 'payment_methods', 'label' => 'Payment Methods', 'required' => true, 'description' => 'Pipe-separated values', 'example' => 'cash|credit_card'],
        ['key' => 'features', 'label' => 'Features', 'required' => false, 'description' => 'Pipe-separated feature names', 'example' => 'GPS|Bluetooth|Heated seats'],
        ['key' => 'essential_plan_price', 'label' => 'Essential Plan Price', 'required' => false, 'description' => 'Optional Essential protection plan price. Must be at least the daily price.', 'example' => '109.00'],
        ['key' => 'essential_plan_features', 'label' => 'Essential Plan Features', 'required' => false, 'description' => 'Optional pipe-separated features for the Essential plan, up to 5.', 'example' => 'Roadside assistance|Theft protection'],
        ['key' => 'essential_plan_description', 'label' => 'Essential Plan Description', 'required' => false, 'description' => 'Optional description for the Essential plan.', 'example' => 'Core protection for standard rentals.'],
        ['key' => 'premium_plan_price', 'label' => 'Premium Plan Price', 'required' => false, 'description' => 'Optional Premium protection plan price. Must be at least the daily price.', 'example' => '139.00'],
        ['key' => 'premium_plan_features', 'label' => 'Premium Plan Features', 'required' => false, 'description' => 'Optional pipe-separated features for the Premium plan, up to 5.', 'example' => 'Zero excess|Glass coverage'],
        ['key' => 'premium_plan_description', 'label' => 'Premium Plan Description', 'required' => false, 'description' => 'Optional description for the Premium plan.', 'example' => 'Extra coverage with reduced excess.'],
        ['key' => 'premium_plus_plan_price', 'label' => 'Premium Plus Plan Price', 'required' => false, 'description' => 'Optional Premium Plus protection plan price. Must be at least the daily price.', 'example' => '169.00'],
        ['key' => 'premium_plus_plan_features', 'label' => 'Premium Plus Plan Features', 'required' => false, 'description' => 'Optional pipe-separated features for the Premium Plus plan, up to 5.', 'example' => 'Full damage waiver|Priority support'],
        ['key' => 'premium_plus_plan_description', 'label' => 'Premium Plus Plan Description', 'required' => false, 'description' => 'Optional description for the Premium Plus plan.', 'example' => 'Highest protection tier for premium bookings.'],
        ['key' => 'custom_addons', 'label' => 'Custom Addons', 'required' => false, 'description' => 'Semicolon-separated addons. Format each addon as name~price~quantity~type~description', 'example' => 'Baby Seat~12.50~1~custom~Child seat;GPS~8.00~1~custom~Navigation unit'],
        ['key' => 'pickup_times', 'label' => 'Pickup Times', 'required' => false, 'description' => 'Pipe-separated HH:MM values', 'example' => '09:00|12:00|16:00'],
        ['key' => 'return_times', 'label' => 'Return Times', 'required' => false, 'description' => 'Pipe-separated HH:MM values', 'example' => '10:00|13:00|17:00'],
        ['key' => 'primary_image_ref', 'label' => 'Primary Image Reference', 'required' => false, 'description' => 'Managed bulk image token or URL from your library', 'example' => 'bulkimg_12345'],
        ['key' => 'gallery_image_refs', 'label' => 'Gallery Image References', 'required' => false, 'description' => 'Pipe-separated managed image tokens or URLs', 'example' => 'bulkimg_12346|bulkimg_12347'],
    ],

    'aliases' => [
        'category' => ['category', 'category_name', 'vehicle_category'],
        'brand' => ['brand', 'make'],
        'model' => ['model'],
        'body_style' => ['body_style', 'body_type'],
        'transmission' => ['transmission', 'gearbox'],
        'fuel' => ['fuel', 'fuel_type'],
        'air_conditioning' => ['air_conditioning', 'aircon', 'ac'],
        'vendor_location_code' => ['vendor_location_code', 'vendor_location', 'location_code', 'location_name', 'vendor_location_name', 'vendor_location_id', 'location_id', 'iata_code'],
        'registration_number' => ['registration_number', 'plate_number'],
        'registration_country' => ['registration_country', 'plate_country'],
        'registration_date' => ['registration_date', 'first_registration_date'],
        'phone_number' => ['phone_number', 'location_phone', 'contact_phone'],
        'security_deposit' => ['security_deposit', 'deposit'],
        'price_per_day' => ['price_per_day', 'daily_price'],
        'price_per_week' => ['price_per_week', 'weekly_price'],
        'weekly_discount' => ['weekly_discount'],
        'price_per_month' => ['price_per_month', 'monthly_price'],
        'monthly_discount' => ['monthly_discount'],
        'price_per_km' => ['price_per_km', 'km_overage_price'],
        'payment_methods' => ['payment_methods', 'payment_method'],
        'essential_plan_price' => ['essential_plan_price', 'essential_price'],
        'essential_plan_features' => ['essential_plan_features', 'essential_features'],
        'essential_plan_description' => ['essential_plan_description', 'essential_description'],
        'premium_plan_price' => ['premium_plan_price', 'premium_price'],
        'premium_plan_features' => ['premium_plan_features', 'premium_features'],
        'premium_plan_description' => ['premium_plan_description', 'premium_description'],
        'premium_plus_plan_price' => ['premium_plus_plan_price', 'premium_plus_price'],
        'premium_plus_plan_features' => ['premium_plus_plan_features', 'premium_plus_features'],
        'premium_plus_plan_description' => ['premium_plus_plan_description', 'premium_plus_description'],
        'custom_addons' => ['custom_addons', 'addons', 'custom_extras', 'extras'],
        'terms_policy' => ['terms_policy', 'terms'],
        'rental_policy' => ['rental_policy', 'policy'],
        'gross_vehicle_mass' => ['gross_vehicle_mass', 'gvm'],
        'vehicle_height' => ['vehicle_height', 'height'],
        'dealer_cost' => ['dealer_cost'],
        'pickup_times' => ['pickup_times', 'pickup_time_slots'],
        'return_times' => ['return_times', 'return_time_slots'],
    ],

    'enums' => [
        'body_style' => ['hatchback', 'sedan', 'coupe', 'sport', 'roadster', 'suv', 'wagon', 'van', 'minivan', 'convertible', 'pickup'],
        'transmission' => ['manual', 'automatic'],
        'fuel' => ['petrol', 'diesel', 'electric', 'hybrid'],
        'status' => ['available', 'rented', 'maintenance'],
        'fuel_policy' => ['full_to_full', 'same_to_same', 'pre_purchase'],
        'payment_methods' => ['cash', 'credit_card', 'bank_wire', 'cheque', 'cryptocurrency'],
    ],
];
